export const CHARACTER_CONDITIONS = {
  INSECURE: 'insecure',
  GUILTY: 'guilty',
  ANGRY: 'angry',
  AFRAID: 'afraid',
  TROUBLED: 'troubled'
}

export const CHARACTER_CONDITION_LABELS = {
  [CHARACTER_CONDITIONS.INSECURE]: 'Insecure',
  [CHARACTER_CONDITIONS.GUILTY]: 'Guilty',
  [CHARACTER_CONDITIONS.ANGRY]: 'Angry',
  [CHARACTER_CONDITIONS.AFRAID]: 'Afraid',
  [CHARACTER_CONDITIONS.TROUBLED]: 'Troubled'
}
