import { MIDJOURNEY_IMAGE_CONTEXTS } from '@shared/constants/artConstants.js'

export const PROGRESSIVE_IMAGE_CONTEXTS = {
  APP_BACKGROUND: {
    preview: MIDJOURNEY_IMAGE_CONTEXTS.MEDIUM,
    final: MIDJOURNEY_IMAGE_CONTEXTS.XLARGE
  },
  CONCEPT_DETAIL_BACKGROUND: {
    preview: MIDJOURNEY_IMAGE_CONTEXTS.MEDIUM,
    final: MIDJOURNEY_IMAGE_CONTEXTS.XLARGE
  },
  FULL_SIZE_MODAL: {
    preview: MIDJOURNEY_IMAGE_CONTEXTS.LARGE,
    final: MIDJOURNEY_IMAGE_CONTEXTS.XLARGE
  },
  BASE_CARD_BACKGROUND: {
    preview: MIDJOURNEY_IMAGE_CONTEXTS.SMALL,
    final: MIDJOURNEY_IMAGE_CONTEXTS.LARGE
  }
}